Branch instructions' tests
izumizawa/mc851 pull request #28
Opened 2023-11-21 00:26 UTC by gabriel-bpro

2023-11-23 03:41 UTC, paulopacitti commented
As operações de branch são feitas na ALU, então essas operações de comparação não fazem sentido.

2023-11-23 23:54 UTC, izumizawa approved these changes

2023-11-24 12:49 UTC, paulopacitti requested changes
Os testes foram feitos um pouco diferentes, mas checa o branch, ficou bom :) Mas tá faltando os testes pro `jal` e `jalr`. Pelo que eu vi na `cpu.v`, parece estar incompleto no seguinte sentido, segue as definições das instruções:

In RISC-V, both jal (Jump and Link) and jalr (Jump and Link Register) are used for control flow operations, specifically for performing jumps within a program.

jal (Jump and Link):
    Operation: jal stands for "Jump and Link." It performs an unconditional jump to the target address specified in the instruction while simultaneously storing the address of the instruction following the jal (the return address) into a specified register (usually ra or x1 in RISC-V).
    Syntax: jal rd, offset
        rd: Destination register where the return address will be stored.
        offset: The signed immediate offset used to calculate the target address relative to the current program counter.
    Example:
```
 jal x1, 100    // Jump to the address 100 and store the return address in x1
```
   Use: jal is commonly used in procedure or function calls within programs. It jumps to the target address, typically the start of a function, and saves the return address, allowing the program to return to the correct location after the function execution.

jalr (Jump and Link Register):
    Operation: jalr stands for "Jump and Link Register." It performs an unconditional jump to the address specified in a register while simultaneously storing the address of the instruction following the jalr (the return address) into a specified register.
    Syntax: jalr rd, rs1, offset
        rd: Destination register where the return address will be stored.
        rs1: Source register containing the target address (the address to jump to).
        offset: The signed immediate offset added to rs1 to calculate the target address.

 Example:
```
    jalr x1, x2, 0   // Jump to the address contained in x2 and store the return address in x1
```

    Use: jalr is more versatile than jal as it allows indirect jumps by specifying the target address in a register. It is used in various scenarios, including function calls, subroutine calls, and implementing jumps through computed addresses.

Use Cases:
    jal is typically used for unconditional direct jumps, often used in function calls or when jumping to specific fixed addresses.
    jalr is used for both direct and indirect jumps, allowing more flexibility in addressing. It's used in scenarios where the target address might be computed or held in a register.

2023-11-28 00:14 UTC, paulopacitti approved these changes
![](https://media.giphy.com/media/dalJ0CpF7hwmN1nZXe/giphy.gif)

2023-11-28 00:42 UTC, guilhermeShima approved these changes

2023-11-28 23:56 UTC, merged